site_name: ArqDsw - EnCare

repo_name: "2020.2_G2_Encare"
repo_url: "https://github.com/UnBArqDsw2020-2/2020.2_G2_Encare"

nav:
  - Home: index.md
  - Base:
    - Projeto Não Orientado a Abordagens Específicas:
      - Glossário: Base/glossario/glossario.md
      - Design Sprint: Base/design_sprint/design_sprint.md
      - Rich Picture: Base/richpicture/rich_picture.md
      - Estimativas: Base/estimativas/estimativas.md
      - Mapa mental: Base/mapa_mental/mapa_mental.md
      - Causa e efeito: Base/causa_e_efeito/causa_e_efeito.md
      - Plano de Ação: Base/planodeacao/5w2g.md
    - Processos/Metodologias/Abordagens:
      - Modelagem BPMN: Base/bpmn/modelagem_bpmn.md
      - Metodologia: Base/metodologia/metodologia.md
theme:
  name: material
  language: pt
  palette:
    primary: blue